### ISSUE TITLE
USER STORY: Love Running - Publish Poll

### ISSUE THREAD

**Issue by somekindofdesign** [somekindofdesign/My-First-Agile-Project#5]
As a **website administrator** I can **publish a poll to the website** so that **users can provide responses**

### Acceptance Criteria
1. I can choose which of the created polls to publish
2. I can add a call-to-action in the form of text to the poll area
3. I can unpublish the poll

### Tasks
- [ ] Generate a list of previously created polls
- [ ] Add radio buttons to the list
- [ ] Add a text field to the publishing area
- [ ] Create publish/unpublish button
- [ ] Test that previous tasks are functional
