### ISSUE TITLE
USER STORY: Love Running - Record Responses

### ISSUE THREAD

**Issue by somekindofdesign** [somekindofdesign/My-First-Agile-Project#6]
As a **website administrator** I can **see poll outcomes** so that **I can analyse the poll results accurately**

### Acceptance Criteria
1. The results should be grouped according to the response options
2. Results should be available as the actual number of responses
3. Results should be available as a percentage of total responses
4. Results should be available in real-time

### Tasks
- [ ] Create a database to record the responses
- [ ] Group the responses
- [ ] Record the answers as numbers and percentages
- [ ] Map the database to an HTML page
- [ ] Print the response to the HTML page
- [ ] Print the response percentages to the HTML page
- [ ] Test that previous tasks are functional
