### ISSUE TITLE
USER STORY: Love Running - Anonymise Poll Response

### ISSUE THREAD

**Issue by somekindofdesign** [somekindofdesign/My-First-Agile-Project#7]
As a **poll respondent** I can **choose to hide my name and email address** so that **my response is anonymous**

### Acceptance Criteria
1. I can choose to add my name and email
2. I can choose to add just my name
3. I can choose to add neither my name or email
4. Anonymisation happens before submission 

### Tasks
- [ ] Add text field for name to poll
- [ ] Add text field for email to poll
- [ ] Add validation to email text field for correct email syntax
- [ ] Add new fields to the poll response database for name / email / anonymous
- [ ] Map new fields to poll results page
- [ ] Test that previous tasks are functional
